"""legal_metadata_and_chunks

Revision ID: 6257374112e3
Revises: 6232a1eb8c5e
"""
import sqlalchemy as sa
from alembic import op

revision = '6257374112e3'
down_revision = '6232a1eb8c5e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('legal_node_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('point_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_model', sa.String(length=300), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_node_id'], ['legal_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_node_id', 'chunk_index'),
    sa.UniqueConstraint('point_id')
    )
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_legal_node_id'), 'document_chunks', ['legal_node_id'], unique=False)
    op.add_column('documents', sa.Column('document_number', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('issued_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('effective_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=200), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('issuing_authority', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('signer', sa.String(length=300), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('documents', sa.Column('previous_version_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=False)
    op.create_foreign_key(None, 'documents', 'documents', ['previous_version_id'], ['id'], ondelete='SET NULL')
    op.alter_column('documents', 'document_number', server_default=None)
    op.alter_column('documents', 'document_type', server_default=None)
    op.alter_column('documents', 'issuing_authority', server_default=None)
    op.alter_column('documents', 'signer', server_default=None)
    op.alter_column('documents', 'summary', server_default=None)
    op.alter_column('documents', 'version_number', server_default=None)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_column('documents', 'previous_version_id')
    op.drop_column('documents', 'version_number')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'signer')
    op.drop_column('documents', 'issuing_authority')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'effective_date')
    op.drop_column('documents', 'issued_date')
    op.drop_column('documents', 'document_number')
    op.drop_index(op.f('ix_document_chunks_legal_node_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
